In [ ]:
import numpy as np




In [ ]:
arr = np.array([[1,2,3], [4,5,6]])

print("arr: \n", arr)
print("arr[-1]: \n", arr[-1])
arr = np.random.randn(20)
print(arr)


try to understand meshgrid

In [ ]:

#create array with values frm -5 to 5, step 0.01, equally distributed
points = np.arange(-5, 5, 0.01)
#print(points)
#print(points.shape, points.ndim)
xs, ys = np.meshgrid(points, points)
#print(xs)
#print(xs.shape, xs.ndim)
points = np.arange(5)
print(points)
xs, ys = np.meshgrid(points, points)
print(xs.shape, xs.ndim)
print("xs:\n", xs)
print("ys:\n", ys)

z = np.sqrt(xs**2 +ys**2)
print(z.shape, z.ndim)
print("z:\n",z)



now, let's look in dot

In [38]:
arr34 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
vec4 = np.arange(4)
res = np.dot(arr34, vec4)
print(res)
#res = np.dot(arr34,arr34)
arr43 = arr34.T
print(arr43)
res = np.dot(arr34,arr43)
print("res:\n", res)
res = np.dot(arr43,arr34)
print("res:\n", res)



[20 44 68]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
res:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
res:
 [[107 122 137 152]
 [122 140 158 176]
 [137 158 179 200]
 [152 176 200 224]]
